name: "Style & Static Analysis"
description: "Verifica el formato del código y busca errores lógicos"

runs:
  using: "composite"
  steps:
    - name: "Clang-Format Check"
      shell: bash
      run: |
        find src include -name "*.cpp" -o -name "*.h" -o -name "*.hpp" | xargs clang-format -n --Werror

    - name: "Cppcheck (Static Analysis)"
      shell: bash
      run: |
        # Creamos una carpeta para el reporte HTML
        mkdir -p cppcheck_report_html
        
        cppcheck  --enable=all \
                  --inline-suppr \
                  --suppress=unmatchedSuppression \
                  --suppress=unusedFunction \
                  --suppress=missingIncludeSystem \
                  --error-exitcode=1 \
                  -I include/ \
                  --xml src/ include/ 2> report.xml

    - name: "Generate HTML Report"
      shell: bash
      if: always()
      run: |
        # Convertimos el XML en una web interactiva (si cppcheck-htmlreport está disponible)
        # Si falla este paso por falta de dependencias, el anterior ya cumplió con el análisis.
        cppcheck-htmlreport --file=report.xml --report-dir=cppcheck_report_html --source-dir=. || echo "HTML report tool not found, skipping."

    - name: "Upload Analysis Report"
      uses: actions/upload-artifact@v4
      if: always() # Queremos el reporte tanto si falló como si pasó
      with:
        name: analysis-results
        # Subimos el XML y la carpeta HTML (si se generó)
        path: |
          report.xml
          cppcheck_report_html/
