#pragma once

#include <numeric>
#include <random>
#include <vector>

#include "PacketBuffer.h"
#include "PageReassembler.h"

class Router;  // Forward declaration

/**
 * @class Terminal
 * @brief Represents a network terminal that can send and receive packets through a connected
 * router. The terminal manages its own input and output buffers, processes incoming packets to
 * reassemble pages, and generates packets for outgoing pages. It also tracks various statistics
 * related to packet and page handling.
 */
class Terminal {
public:
    /** Default input processing rate for the terminal */
    static constexpr size_t DEF_INPUT_PROC  = 10;
    /** Default output bandwidth for the terminal */
    static constexpr size_t DEF_OUTPUT_BW   = 5;
    /** Default output buffer capacity for the terminal */
    static constexpr size_t DEF_OUT_BUF_CAP = 0;
    /** Default input buffer capacity for the terminal */
    static constexpr size_t DEF_IN_BUF_CAP  = 0;

    /**
     * @struct Config
     * @brief Represents configuration settings for buffering and processing in a system.
     *
     * This structure is used to define the capacity of input and output buffers, as well
     * as the bandwidth and processing constraints.
     */
    struct Config {
        /** Input buffer capacity for the terminal */
        size_t inBufferCap;
        /** Input processing rate, packets that can be processed from the input buffer per cycle */
        size_t inProcCap;
        /** Output buffer capacity for the terminal */
        size_t outBufferCap;
        /** Output bandwidth, number of packets that can be sent to the router per cycle */
        size_t outputBW;

        /**
         * @brief Default constructor for Config, initializes with default values.
         */
        Config()
            : inBufferCap(DEF_IN_BUF_CAP),
              inProcCap(DEF_INPUT_PROC),
              outBufferCap(DEF_OUT_BUF_CAP),
              outputBW(DEF_OUTPUT_BW) {}

        /**
         * @brief Parameterized constructor for Config struct that allows custom settings.
         *
         * @param inBufferCap Input buffer capacity.
         * @param inProcCap Input processing rate (packets per cycle).
         * @param outBufferCap Output buffer capacity.
         * @param outputBW Output bandwidth (packets per cycle).
         */
        Config(size_t inBufferCap, size_t inProcCap, size_t outBufferCap, size_t outputBW)
            : inBufferCap(inBufferCap),
              inProcCap(inProcCap),
              outBufferCap(outBufferCap),
              outputBW(outputBW) {}
    };

private:
    /**
     * @struct QuarantinedID
     * @brief Represents a page ID currently quarantined due to an expired reassembler.
     */
    struct QuarantinedID {
        size_t pageID;  /**< ID of the discarded page */
        size_t timeout; /**< System tick when this quarantine entry expires */
    };
    /** List of active page reassemblers currently processing incoming packets */
    using AssemblerList   = std::vector<PageReassembler>;
    /** List of page IDs that are currently quarantined due to expired reassemblers */
    using QuarantinedList = std::vector<QuarantinedID>;

    IPAddress terminalIP; /**< IP address of the terminal */
    Router* rtrConn;      /**< Pointer to the router connected to the terminal */

    PacketBuffer inBuffer;  /**< Queue for incoming packets */
    size_t inProcCap;       /**< Packets per cycle able to process from the input buffer */
    PacketBuffer outBuffer; /**< Queue for outgoing packets */
    size_t outBW;           /**< Packets per cycle able to send to router */

    AssemblerList reassemblers; /**< Active page reassemblers */

    size_t pagesCreated;    /**< Total pages created and sent by this terminal */
    size_t pagesSent;       /**< Total pages sent to router */
    size_t pagesOutDropped; /**< Total pages dropped due to output buffer overflow */
    size_t pagesCompleted;  /**< Total pages successfully reassembled by the terminal */
    size_t pagesTimedOut;   /**< Total pages dropped due to expired reassemblers */

    size_t packetsGenerated;   /**< Packets generated by this terminal */
    size_t packetsSent;        /**< Packets sent to router */
    size_t packetsOutDropped;  /**< Packets dropped due to output buffer overflow */
    size_t packetsOutTimedOut; /**< Packets dropped due to expiration while in the output buffer */

    size_t packetsReceived;      /**< Packets received from router */
    size_t packetsInTimedOut;    /**< Packets dropped due to expired packets or reassemblers */
    size_t packetsInDropped;     /**< Packets dropped due to input buffer overflow */
    size_t packetsSuccProcessed; /**< Packets successfully reassembled into pages */

    size_t nextPageID; /**< ID for the next page to be sent */

    QuarantinedList quarantine; /**< List of page IDs that are currently quarantined due to expired
                                   reassemblers */
    List<IPAddress>* addressBook; /**< Pointer to the network's address book */
    float trafficProbability;     /**< Probability of generating a page in each tick */
    size_t maxPageLen;            /**< Maximum number of packets in a page for traffic generation */
    std::mt19937* m_gen;          /**< Random number generator for traffic generation */

public:
    /**
     * @brief Constructor for Terminal.
     *
     * @param terminalID Terminal's unique ID within the router (must be > 0).
     * @param router Pointer to connected router.
     * @param cfg Configuration struct for bandwidth and buffer settings (optional).
     */
    Terminal(Router* router, uint8_t terminalID, const Config& cfg = Config{});

    /**
     * @brief Destructor - cleans up all active reassemblers.
     */
    ~Terminal() = default;

    /**
     * @brief Copy constructor - deleted to prevent copying.
     */
    Terminal(const Terminal&) = delete;

    /**
     * @brief Copy assignment operator - deleted to prevent copying.
     *
     * @return Reference to this terminal.
     */
    Terminal& operator=(const Terminal&) = delete;

    /**
     * @brief Move constructor - deleted to prevent moving.
     */
    Terminal(Terminal&&) = delete;

    /**
     * @brief Move assignment operator - deleted to prevent moving.
     *
     * @return Reference to this terminal.
     */
    Terminal& operator=(Terminal&&) = delete;

    // =============== Transmission ===============
    /**
     * @brief Creates a page and fragments it into packets for transmission.
     *
     * Checks if the output buffer has enough space for all packets. If not, the page is dropped and
     * statistics are updated. If successful, packets are enqueued in the output buffer and
     * statistics are updated.
     *
     * @param length Number of packets on the page (must be > 0).
     * @param destIP Destination IP address.
     * @param timeout System tick when the packets should expire.
     * @return true if the page was successfully created and enqueued, false if dropped due to
     * insufficient buffer space.
     */
    bool sendPage(size_t length, IPAddress destIP, size_t timeout);

    /**
     * @brief Receives a packet from the network.
     *
     * @param packet The packet to receive.
     * @return true if a packet was buffered, false if dropped due to quarantine or input buffer
     * overflow.
     */
    bool receivePacket(const Packet& packet);

    // =============== Processing ===============
    /**
     * @brief Processes up to internalProc packets from the input buffer, attempting to reassemble
     * pages.
     *
     * @param currentTick The current system tick for processing timeouts and expirations.
     * @return Number of packets actually processed.
     */
    size_t processInputBuffer(size_t currentTick);

    /**
     * @brief Processes up to outBW packets from the output buffer, sending them to the connected
     * router.
     *
     * @param currentTick The current system tick for processing timeouts and expirations.
     * @return Number of packets actually sent to the router.
     */
    size_t processOutputBuffer(size_t currentTick);

    /**
     * @brief Advances the terminal's state by one tick, processing input and output buffers and
     * updating reassemblers and quarantine.
     *
     * @param currentTick The current system tick for processing timeouts and expirations.
     */
    void tick(size_t currentTick);

    /**
     * @brief Generates traffic by randomly deciding to create and send a page based on the traffic
     * probability. If a page is generated, it will have a random length up to maxPageLen and a
     * random destination IP from the address book.
     *
     * @param currentTick The current system tick for processing timeouts and expirations.
     */
    void generateTraffic(size_t currentTick);
    //  =============== Setters ===============
    /**
     * @brief Sets external bandwidth.
     *
     * @param bw New bandwidth value.
     */
    void setExternalBW(size_t bw) noexcept;

    /**
     * @brief Sets internal processing capacity.
     *
     * @param capacity New bandwidth value.
     */
    void setInternalProc(size_t capacity) noexcept;

    /**
     * @brief Sets the address book pointer for the terminal.
     *
     * @param addBook Pointer to the network's address book.
     */
    void setAddressBook(List<IPAddress>* addBook) noexcept;

    /**
     * @brief Sets the random number generator for traffic generation.
     *
     * @param gen Pointer to a std::mt19937 random number generator.
     */
    void setRandomGenerator(std::mt19937* gen) noexcept;

    /**
     * @brief Sets the probability of generating traffic in each tick.
     *
     * @param probability New traffic generation probability (0.0 to 1.0).
     */
    void setTrafficProbability(float probability) noexcept;

    /**
     * @brief Sets the maximum page length for traffic generation.
     *
     * @param pageLen New maximum page length (number of packets).
     */
    void setMaxPageLength(size_t pageLen) noexcept;

    // =============== Getters ===============
    /**
     * @brief Gets the terminal's IP address.
     *
     * @return Terminal's IP address.
     */
    [[nodiscard]] IPAddress getTerminalIP() const noexcept;

    /**
     * @brief Gets the output bandwidth.
     *
     * @return External bandwidth value.
     */
    [[nodiscard]] size_t getOutputBW() const noexcept;

    /**
     * @brief Gets the internal processing capacity.
     *
     * @return Internal bandwidth value.
     */
    [[nodiscard]] size_t getInternalProc() const noexcept;

    /**
     * @brief Gets the total number of pages created and sent by this terminal.
     *
     * @return Total pages created.
     */
    [[nodiscard]] size_t getPagesCreated() const noexcept;

    /**
     * @brief Gets the total number of pages sent to the router.
     *
     * @return Total pages sent.
     */
    [[nodiscard]] size_t getPagesSent() const noexcept;

    /**
     * @brief Gets the total number of pages dropped due to output buffer overflow.
     *
     * @return Total pages dropped.
     */
    [[nodiscard]] size_t getPagesDropped() const noexcept;

    /**
     * @brief Gets the total number of pages successfully reassembled by the terminal.
     *
     * @return Total pages completed.
     */
    [[nodiscard]] size_t getPagesCompleted() const noexcept;

    /**
     * @brief Gets the total number of pages dropped due to expired reassemblers.
     *
     * @return Total pages timed out.
     */
    [[nodiscard]] size_t getPagesTimedOut() const noexcept;

    /**
     * @brief Gets the total number of packets generated by this terminal.
     *
     * @return Total packets generated.
     */
    [[nodiscard]] size_t getPacketsGenerated() const noexcept;

    /**
     * @brief Gets the total number of packets sent to the router.
     *
     * @return Total packets sent.
     */
    [[nodiscard]] size_t getPacketsSent() const noexcept;

    /**
     * @brief Gets the total number of packets dropped due to output buffer overflow.
     *
     * @return Total packets dropped.
     */
    [[nodiscard]] size_t getPacketsOutDropped() const noexcept;

    /**
     * @brief Gets the total number of packets dropped due to expiration while in the output buffer.
     *
     * @return Total packets timed out in the output buffer.
     */
    [[nodiscard]] size_t getPacketsOutTimedOut() const noexcept;

    /**
     * @brief Gets the number of packets currently pending in the output buffer.
     *
     * @return Number of packets pending in the output buffer.
     */
    [[nodiscard]] size_t getPacketsOutPending() const noexcept;

    /**
     * @brief Gets the total number of packets received from the router.
     *
     * @return Total packets received.
     */
    [[nodiscard]] size_t getPacketsReceived() const noexcept;

    /**
     * @brief Gets the total number of packets dropped due to expired packets or reassemblers.
     *
     * @return Total packets dropped on input.
     */
    [[nodiscard]] size_t getPacketsInTimedOut() const noexcept;

    /**
     * @brief Gets the total number of packets dropped due to input buffer overflow.
     *
     * @return Total packets dropped on input.
     */
    [[nodiscard]] size_t getPacketsInDropped() const noexcept;

    /**
     * @brief Gets the total number of packets successfully reassembled into pages.
     *
     * @return Total packets successfully processed.
     */
    [[nodiscard]] size_t getPacketsSuccProcessed() const noexcept;

    /**
     * @brief Gets the number of packets currently pending in the input buffer and reassemblers.
     *
     * @return Number of packets pending on input.
     */
    [[nodiscard]] size_t getPacketsInPending() const noexcept;

    /**
     * @brief Gets the probability of generating traffic in each tick.
     *
     * @return Traffic generation probability (0.0 to 1.0).
     */
    [[nodiscard]] float getTrafficProbability() const noexcept;

    /**
     * @brief Gets the maximum page length for traffic generation.
     *
     * @return Maximum page length (number of packets).
     */
    [[nodiscard]] size_t getMaxPageLength() const noexcept;

    /**
     * @brief Gets a pointer to the random number generator used for traffic generation.
     *
     * @return Pointer to the std::mt19937 random number generator.
     */
    [[nodiscard]] std::mt19937* getRandomGenerator() const noexcept;

    /**
     * @brief Generates a string representation of the terminal, including its IP address.
     *
     * @return A string representation of the terminal
     */
    [[nodiscard]] std::string toString() const;

    /**
     * @brief Stream output operator for Terminal.
     *
     * @param os Output stream to write to.
     * @param terminal The terminal to output.
     * @return Reference to the output stream.
     */
    friend std::ostream& operator<<(std::ostream& os, const Terminal& terminal);

private:
    // =============== Private helpers ===============
    /**
     * @brief Finds an existing reassembler for the given page ID or creates a new one if it doesn't
     * exist.
     *
     * @param pageID ID of the page being reassembled.
     * @param srcIP Source IP address of the page being reassembled.
     * @param pageLength Total number of packets expected for the page.
     * @param timeout System tick when the reassembler should expire.
     * @return Pointer to the found or created PageReassembler, or nullptr if a reassembler exists
     * but has a different expected page length.
     */
    PageReassembler* findOrCreateReassembler(size_t pageID, IPAddress srcIP, size_t pageLength,
                                             size_t timeout);

    /**
     * @brief Handles a completed page by packaging it and updating statistics.
     *
     * @param pageID ID of the completed page.
     * @param srcIP Source IP address of the completed page.
     */
    void handleCompletedPage(size_t pageID, IPAddress srcIP);

    /**
     * @brief Cleans up expired reassemblers and updates statistics and quarantine list accordingly.
     *
     * @param currentTick The current system tick for processing expirations.
     */
    void cleanupReassemblers(size_t currentTick);

    /**
     * @brief Updates the quarantine list by removing expired entries.
     *
     * @param currentTick The current system tick for processing expirations.
     */
    void updateQuarantine(size_t currentTick);

    /**
     * @brief Checks if a given page ID is currently quarantined.
     *
     * @param id Page ID to check.
     * @return true if the page ID is in quarantine, false otherwise.
     */
    [[nodiscard]] bool isIDQuarantined(size_t id) const;
};

inline size_t Terminal::getPagesCreated() const noexcept {
    return pagesCreated;
}

inline size_t Terminal::getPagesSent() const noexcept {
    return pagesSent;
}

inline size_t Terminal::getPagesDropped() const noexcept {
    return pagesOutDropped;
}

inline size_t Terminal::getPagesCompleted() const noexcept {
    return pagesCompleted;
}

inline size_t Terminal::getPagesTimedOut() const noexcept {
    return pagesTimedOut;
}

inline size_t Terminal::getPacketsGenerated() const noexcept {
    return packetsGenerated;
}

inline size_t Terminal::getPacketsSent() const noexcept {
    return packetsSent;
}

inline size_t Terminal::getPacketsOutDropped() const noexcept {
    return packetsOutDropped;
}

inline size_t Terminal::getPacketsOutTimedOut() const noexcept {
    return packetsOutTimedOut;
}

inline size_t Terminal::getPacketsOutPending() const noexcept {
    return outBuffer.size();
}

inline size_t Terminal::getPacketsReceived() const noexcept {
    return packetsReceived;
}

inline size_t Terminal::getPacketsInTimedOut() const noexcept {
    return packetsInTimedOut;
}

inline size_t Terminal::getPacketsInDropped() const noexcept {
    return packetsInDropped;
}

inline size_t Terminal::getPacketsSuccProcessed() const noexcept {
    return packetsSuccProcessed;
}

inline size_t Terminal::getPacketsInPending() const noexcept {
    const size_t pending = std::accumulate(
        reassemblers.begin(), reassemblers.end(), 0,
        [](const size_t sum, const PageReassembler& r) { return sum + r.getReceivedPackets(); });

    return pending + inBuffer.size();
}

inline float Terminal::getTrafficProbability() const noexcept {
    return trafficProbability;
}

inline size_t Terminal::getMaxPageLength() const noexcept {
    return maxPageLen;
}

inline std::mt19937* Terminal::getRandomGenerator() const noexcept {
    return m_gen;
}

inline IPAddress Terminal::getTerminalIP() const noexcept {
    return terminalIP;
}

inline size_t Terminal::getOutputBW() const noexcept {
    return outBW;
}

inline size_t Terminal::getInternalProc() const noexcept {
    return inProcCap;
}

inline void Terminal::setExternalBW(size_t bw) noexcept {
    outBW = bw;
}

inline void Terminal::setInternalProc(size_t capacity) noexcept {
    inProcCap = capacity;
}

inline void Terminal::setAddressBook(List<IPAddress>* addBook) noexcept {
    addressBook = addBook;
}

inline void Terminal::setRandomGenerator(std::mt19937* gen) noexcept {
    m_gen = gen;
}

inline void Terminal::setTrafficProbability(float probability) noexcept {
    trafficProbability = probability;
}

inline void Terminal::setMaxPageLength(size_t pageLen) noexcept {
    maxPageLen = pageLen;
}
